// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyNHCEHLYTi3TL2vHU9Ts72sAb8lELazg',
    appId: '1:343562754685:web:e9bff5295a4e9e501c2f14',
    messagingSenderId: '343562754685',
    projectId: 'feelancingplatform',
    authDomain: 'feelancingplatform.firebaseapp.com',
    storageBucket: 'feelancingplatform.appspot.com',
    measurementId: 'G-H96R75XKQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVYoDNBusAPcywOu2-UhKshszqiYqJ3H8',
    appId: '1:343562754685:android:68aeda2fca7177a41c2f14',
    messagingSenderId: '343562754685',
    projectId: 'feelancingplatform',
    storageBucket: 'feelancingplatform.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyNHCEHLYTi3TL2vHU9Ts72sAb8lELazg',
    appId: '1:343562754685:web:53485cb8d69859f11c2f14',
    messagingSenderId: '343562754685',
    projectId: 'feelancingplatform',
    authDomain: 'feelancingplatform.firebaseapp.com',
    storageBucket: 'feelancingplatform.appspot.com',
    measurementId: 'G-FF78RXG9KL',
  );
}
